### PR TITLE
chore: add a panel completions keybinding example

### PR DESCRIPTION
**Pull request by jfcherng**
closes https://github.com/TerminalFi/LSP-copilot/issues/88

### CODE REVIEW

**Comment by TerminalFi** [comment]
Should we add `copilot_close_panel_completion`

**Review by TerminalFi — APPROVED** [review]

**Comment by jfcherng** [comment]
Added!

**Comment by jfcherng** [comment]
Wait. I think the "context" is a problem.

**Review by timfjord — APPROVED** [review]

**Comment by TerminalFi** [comment]
LTGM

**Pull request merged**
