### PR TITLE
feat: add fetching user icon

### PR DESCRIPTION
**Pull request by TerminalFi**
Perhaps we can refine the fetching of icons and setting of account status

TerminalFi 2024-07-03 at 21 35 42@2x

### CODE REVIEW

**Comment by TerminalFi** [comment]
Hmm I will leave the types issue to you @jfcherng I am not familiar enough for this :P

**Comment by jfcherng** [comment]
Now, I don't understand why I keep getting `Parse Error at line 341 column 34: closing p does not match opening span` when chatting.

**Comment by jfcherng** [comment]
> Now, after refactoring, I don't understand why I keep getting `Parse Error at line 341 column 34: closing p does not match opening span` when chatting.

OK. Fixed.

**Comment by TerminalFi** [comment]
Your refactor looks wayyyyyy better 

LGTM

**Pull request merged**
