### PR TITLE
feat: activity indicator

### PR DESCRIPTION
**Pull request by TerminalFi**
https://github.com/TerminalFi/LSP-copilot/assets/32599364/e3e4c003-ec0c-40ae-b19b-32c7e90de4bd

### CODE REVIEW

**Comment by TerminalFi** [comment]
Not sure if this is the best implementation. Inspired by Package Control. However, simplified

**Comment by TerminalFi** [comment]
Addresses #166

**Comment by jfcherng** [comment]
LGTM.

**Comment by jfcherng** [comment]
lol I actually found it makes the status bar quite distracting

**Comment by TerminalFi** [comment]
> lol I actually found it makes the status bar quite distracting

Maybe we hide behind a setting ?

**Comment by jfcherng** [comment]
Or maybe we show it when the time elapses a threshold. E.g., it only shows when waiting time \> 1 second.

**Pull request merged**
